FROM gigary/base:3.4
MAINTAINER Michael Bui <mf.michaelbui@gmail.com>

RUN apk add --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted \
    php5-fpm php5-cli php5-mysql php5-pdo_mysql \
    php5-mcrypt php5-curl php5-json php5-ctype php5-zlib php5-dom php5-xml php5-openssl \
    php5-phar php5-xdebug

RUN rm -rf /var/cache/apk/*

ADD root /

EXPOSE 9000

